language: java
install: true   # tells Travis that we run gradlew manually
jdk:
- openjdk8
env:
  - JAVA_INC=/usr/lib/jvm/java-8-openjdk-amd64/include
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_install:
  - chmod +x install_mcl.sh
  - ./install_mcl.sh $JAVA_INC

before_script:
  git checkout ${TRAVIS_BRANCH}

stages:
- name: build
- name: release
  if: branch = release

jobs:
  include:
  - stage: build
    script: "./gradlew build -PcheckoutIfCloned=true"
  - stage: release
    script: "./gradlew publish -x test -Dnexus.user=$NEXUS_USER -Dnexus.key=$NEXUS_KEY -Dbuild.number=$TRAVIS_BUILD_NUMBER"

deploy:
  provider: releases
  api_key:
    secure: dZzO5HrovScF//eLWLH+kCKZR7PWMt3epAwKM2RcS1KKZCpXeiD+4aTL/SAivoeFUZ+25E5cD5C5WbxImGHaTjrcV8m3WW1O5SqVYFfHz1xcsDJekCsm6YyV4xQo7e22X1+xK2ZTQ40b8PwwgXHsMsRYYZuAZu4dOfLLhDcFiYJHlvQ3UT7SetKsKo+iev7e8d1lKb9fIR0SA9CCo/DxmTsFbu4pl+OgpxrLTPYnEO1QIBmus7uZYG9w0laLJ2UMFO7agwhN4b4DTEwkHKuQrSynKIaUxeaVCctSS1X/ldwFWJ1OqdUitL+kjhM+STEZU45Y5E11w78lcAkiqcHCss2Dbhe83QFsOGShvBnE/tBrD3uH6Uhqj01sRVF8xzkETLrobyoavUPgzUXdExcsHu+MGZWO/CC/nHxpxXkH9lnidC0dYlh4lpci2FbNIX9lSdS5KyzbUdy4pJKaz9z6UewPF719QPVqo/uyJfsx+tRS7LBk8m+i2Le36KG7gd1Vu2N+8BmJRbJ/8gmqdLfufuDEINdHH0P4VlR9/VXnaWiz4+W9cOlL7iw439vUl+BJsq/0904Hh207dArGXD7ypxZQ7WvEeLZJOfZPsnIPhrbGQKTTrlyacNLo8heAOD4lz1o4Pt8EGblLHpJ4ScgqbcoeNvyc0/36dJyk0J5OQE4=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    repo: upbcuk/upb.crypto.mclwrap
    branch: release
