name: Java CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Mcl Java bindings
        run: |
          chmod +x install_mcl.sh
          ./install_mcl.sh $JAVA_HOME/include
      - name: Build with Gradle
        run: ./gradlew build -PcheckoutIfCloned=true