name: "manual github release"

on: 
  workflow_dispatch:

jobs:
  release:
    name: "github release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Build & test"
        run: |
          echo "done!"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true
          files: |
            LICENSE
            build/libs/*.jar
        id: "automatic_releases"
